version: 2.1
orbs:
  docker: circleci/docker@2.1.2
  node: circleci/node@5.0.2

executors:
  node_16:
    docker:
      - image: cimg/node:16.16.0

parameters:
  proxy:
    type: boolean
    default: false

  services:
    type: boolean
    default: false

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn

  build_monorepo: &build_monorepo
    run:
      name: Build monorepo
      command: yarn build

  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

commands:
  build_proxy:
    steps:
      - docker/build:
          path: packages/proxy
          image: $CIRCLE_PROJECT_REPONAME/proxy
  build_services:
    steps:
      - docker/build:
          path: packages/services
          image: $CIRCLE_PROJECT_REPONAME/services

jobs:
  build_images:
    executor: node_16
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *build_monorepo
      - <<: *save_cache
      - when:
          condition: << pipeline.parameters.proxy >>
          steps:
            - build_proxy
      - when:
          condition: << pipeline.parameters.services >>
          steps:
            - build_services

workflows:
  build_images_workflow:
    when:
      or: [<< pipeline.parameters.proxy >>, << pipeline.parameters.services >>]
    jobs:
      - build_images
