version: 2.1
orbs:
  docker: circleci/docker@2.1.2
  node: circleci/node@5.0.2

parameters:
  proxy:
    type: boolean
    default: false

  services:
    type: boolean
    default: false

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn

  build_monorepo: &build_monorepo
    run:
      name: Build monorepo
      command: yarn build

  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

commands:
  build_proxy:
    steps:
      - docker/publish:
          path: packages/proxy
          deploy: false
          image: $CIRCLE_PROJECT_REPONAME/proxy
  build_services:
    steps:
      - docker/publish:
          path: packages/services
          deploy: false
          image: $CIRCLE_PROJECT_REPONAME/services

jobs:
  build_images:
    executor:
      name: node/default
      tag: "16.17.0"
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *build_monorepo
      - <<: *save_cache
      - when:
          condition: << pipeline.parameters.proxy >>
          steps:
            - build_proxy
      - when:
          condition: << pipeline.parameters.services >>
          steps:
            - build_services

workflows:
  build_images_workflow:
    jobs:
      - build_images
