version: 2.1
orbs:
  docker: circleci/docker@2.1.2

parameters:
  proxy:
    type: boolean
    default: false

  services:
    type: boolean
    default: false

jobs:
  build_proxy:
    - docker/publish:
        path: packages/proxy
        deploy: false
        image: $CIRCLE_PROJECT_REPONAME/proxy
  build_services:
    - docker/publish:
        path: packages/services
        deploy: false
        image: $CIRCLE_PROJECT_REPONAME/services
  build_images:
    steps:
      - when:
          condition: << pipeline.parameters.proxy >>
          steps:
            - build_proxy
      - when:
          condition: << pipeline.parameters.services >>
          steps:
            - build_services

workflows:
  build_images_workflow:
    jobs:
      - build_images
